version: '3.9'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  redis:
    image: redis:7